# Site settings
title: Francisco
header-img: img/yesterday.png
description: "Francisco Sousa"
baseurl: ""
url: "/"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
